CREATE DATABASE Teste1

CREATE TABLE TbAppTeste
(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	nome VARCHAR(10),
	sobrenome VARCHAR(20),
	sexo VARCHAR(2)
)

CREATE PROCEDURE sp_SELECAO 
AS
BEGIN
	SELECT * FROM TbAppTeste;
END
GO

CREATE PROCEDURE sp_INSERCAO
@nome VARCHAR(10),
@sobrenome VARCHAR(20),
@sexo VARCHAR(2)
AS
BEGIN
	INSERT INTO TbAppTeste VALUES (@nome,@sobrenome,@sexo);
END
GO