CREATE TABLE TbAppTeste
(
	id INT NOT NULL PRIMARY KEY,
	nome VARCHAR(10),
	sobrenome VARCHAR(20),
	sexo VARCHAR(2)
)

DROP TABLE TbAppTeste

CREATE TABLE TbAppTeste
(
	id INT NOT NULL PRIMARY KEY IDENTITY,
	nome VARCHAR(10),
	sobrenome VARCHAR(20),
	sexo VARCHAR(2)
)

SELECT * FROM TbAppTeste

DELETE FROM TbAppTeste WHERE id = 4

COMMIT TRANSACTION